name: winequality prediction v1

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        black . --check --diff
  test_integration_ci:
    runs-on: ubuntu-latest
    needs: build_ci
    steps:
    - name: Test with pytest
      run: |
        pytest -v
